---
number-sections: false
---

# About this guide

This book/site provides a guide to implementing *Adaptive Preregistration for Model-Based Research*, with a focus on ecological modelling as it is used in both basic and applied contexts. This site covers the following topics:

1.  [Background on researcher degrees of freedom](RDF_QRP.qmd), the risk of questionable research practices (QRPs), and introduction to preregistration as a tool for mitigating QRPs and improving transparency.
2.  Adaptive Preregistration
    1.  [*Overview*](adaptive_preregistration_background.qmd): What is adaptive preregistration, why do we need it for registering modelling analyses, and what are its defining features?
    2.  [*A practical guide*](adaptive_preregistration_implementation.qmd): How to implement adaptive preregistration using [git](https://git-scm.com) and [GitHub](www.github.com).
3.  [Preregistration template](preregistration_modelling.qmd) for model-based research in ecology and conservation.

This practical guide accompanies the paper:

> Gould, E., Jones, C.S., Yen, J.D.L., Fraser, H.S., Wootton, H., Good, M.K., Duncan, D.H., Hauser, C.E., Wintle, B.C., Rumpff, L. (in prep., 2026) "But I can't preregister my research: Improving the reproducibility and transparency of ecological modelling with adaptive preregistration". EcoEvoArXiv \[Preprint\]. <https://doi.org/10.32942/X2GW66>

Please cite this guide as:

> Gould, E., Jones, C.S., Yen, J.D.L., Fraser, H.S., Wootton, H., Good, M.K., Duncan, D.H., Hauser, C.E., Wintle, B.C., Rumpff, L. & Fidler, F. (2026). EcoConsPreReg: A Guide to Adaptive Preregistration for Model-Based Research in Ecology and Conservation. Zenodo. [https://doi.org/10.5281/zenodo.19064144](https://doi.org/10.5281/zenodo.10807029)
