# This is a basic workflow to help you get started with Actions

name: RenderRmarkdown

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: rstudio/r-base:3.6-bionic

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update && apt-get install -y --no-install-recommends \
        libxml2-dev \
        libssl-dev \
        libcurl4-openssl-dev
        sudo apt-get install pandoc
        
    - name: Install R Package Dependencies
      run: |
        Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
        Rscript -e "install.packages('rmarkdown', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
        Rscript -e "install.packages('knitr', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
        Rscript -e "install.packages('distill', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"

    - name: Where am I and what is here
      run: |
        pwd
        ls -f

    - name: Knit Rmarkdown Documents
      run: |
        Rscript -e "rmarkdown::render(input = 'index.Rmd')"
